steps:
  # Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-497413/auth-service/productions', '-f', 'services/auth-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-497413/auth-service/productions']

  # Notification Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-497413/notification-service/productions', '-f', 'services/notification-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-497413/notification-service/productions']

  # Orders Service
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-497413/order-service/productions', '-f', 'services/orders-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-497413/order-service/productions']

  # Payments Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-497413/payments-service/productions', '-f', 'services/payments-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-497413/payments-service/productions']

  # Product Services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-497413/products/productions', '-f', 'services/products/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-497413/products/productions']
options:
  logging: CLOUD_LOGGING_ONLY