steps:
  # Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-499513/auth-service/production', '-f', 'services/auth-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-499513/auth-service/production']

  # Notification Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-499513/notification-service/production', '-f', 'services/notification-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-499513/notification-service/production']

  # Orders Service
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-499513/orders-service/production', '-f', 'services/orders-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-499513/orders-service/production']

  # Payments Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-499513/payments-service/production', '-f', 'services/payments-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-499513/payments-service/production']

  # Product Services
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/ecommerce-499513/products/production', '-f', 'services/products/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/ecommerce-499513/products/production']
options:
  logging: CLOUD_LOGGING_ONLY