apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    minSize: 5
    maxSize: 8
    desiredCapacity: 6