services:
  products:
    build:
      context: .
      dockerfile: ./services/products/Dockerfile
      target: runner
    command: pnpm run dev
    container_name: Products_Service
    env_file:
      - ./services/products/.env
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
      target: runner
    # mem_limit: 1g
    # memswap_limit: 2g
    command: pnpm run dev
    container_name: Auth_Service
    env_file:
      - ./services/auth-service/.env
      - .env
    ports:
      - '5001:5001'
    expose:
      - '5002' #TCP port
    volumes:
      - .:/usr/src/app
  payments-service:
    build:
      context: .
      dockerfile: ./services/payments-service/Dockerfile
      target: runner
    # mem_limit: 1g
    # memswap_limit: 2g
    command: pnpm run dev
    container_name: Payments_Service
    env_file:
      - ./services/payments-service/.env
    ports:
      - '5003:5003'
    expose:
      - '5004' #TCP port
    volumes:
      - .:/usr/src/app

  orders-service:
    build:
      context: .
      dockerfile: ./services/orders-service/Dockerfile
      target: runner
    # mem_limit: 1g
    # memswap_limit: 2g
    command: pnpm run dev
    container_name: Orders_Service
    env_file:
      - ./services/orders-service/.env
    ports:
      - '5005:5005'
    expose:
      - '5006' #TCP port
    volumes:
      - .:/usr/src/app

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
      target: runner
    # mem_limit: 1g
    # memswap_limit: 2g
    command: pnpm run dev
    container_name: Notification_Service
    env_file:
      - ./services/notification-service/.env
    ports:
      - '5007:5007' #no need to expose the port if connected with TCP
    expose:
      - '5008' #TCP port
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
