apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: asia-south1-docker.pkg.dev/ecommerce-499513/notification-service/production
        imagePullPolicy: Always
        command: ["node"]
        args: ["services/notification-service/dist/main"]
        env:
         - name: NODE_ENV
           value: development
         - name: NOTIFICATION_SERVICE_APP_NAME
           value: Notification Service
         - name: NOTIFICATION_SERVICE_APP_PORT
           value: "5007"
         - name:  NOTIFICATION_TCP_PORT
           value: "5008"
         - name: GOOGLE_OAUTH_CLIENT_ID
           value: "739344659399-vaffnnmgbn0jh2bm70boaq2d5650m4n4.apps.googleusercontent.com"
         - name: SMTP_USER
           value: "steadybuy.app@gmail.com"
         - name: GOOGLE_OAUTH_CLIENT_SECRET
           valueFrom:
             secretKeyRef:
               name: google
               key: clientSecret
         - name: GOOGLE_OAUTH_REFRESH_TOKEN
           valueFrom:
             secretKeyRef:
               name: google
               key: refreshToken
        ports:
          - containerPort: 5007 #if http port not required then remove this
          - containerPort: 5008
      #Keeping both ports for now as notification service is also sending http request to payment service. If http port not required then remove this and also remove from service.yaml
