apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service-http
spec:
  ports:
  - name: "http"
    port: 5007
    protocol: TCP
    targetPort: 5007
  selector:
    app: notification-service
  type: NodePort
