apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-service
  name: notifications-service-tcp
spec:
  ports:
  - name: "tcp"
    port: 5008
    protocol: TCP
    targetPort: 5008
  selector:
    app: notifications-service
  type: ClusterIP
