apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-service
  name: notifications-service-http
spec:
  ports:
  - name: "http"
    port: 5007
    protocol: TCP
    targetPort: 5007
  selector:
    app: notifications-service
  type: NodePort
