apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-service
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: asia-south1-docker.pkg.dev/ecommerce-497413/order-service/productions
        imagePullPolicy: Always
        command: ["node"]
        args: ["services/orders-service/dist/src/main"]
        env:
         - name: MONGODB_URI
           valueFrom:
            secretKeyRef:
              name: mongodb
              key: connectionString
         - name: NODE_ENV
           value: development
         - name: ORDERS_SERVICE_APP_NAME
           value: Orders Service
         - name: ORDERS_SERVICE_APP_PORT
           value: "5005"
         - name: ORDERS_TCP_PORT
           value: "5006"
         - name: AUTH_HOST
           value: auth-service-tcp
         - name: AUTH_SERVICE_TCP_PORT
           value: "5002"
         - name: PAYMENTS_HOST
           value: payments-service
         - name: PAYMENTS_TCP_PORT
           value: "5004"
        ports:
          - containerPort: 5005 #If http port not required then remove this
          - containerPort: 5006