apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: asia-south1-docker.pkg.dev/ecommerce-497413/products/productions
        imagePullPolicy: Always
        command: ["node"]
        args: ["services/products/dist/src/main"]
        env:
         - name: MONGODB_URI
           valueFrom:
            secretKeyRef:
              name: mongodb
              key: connectionString
         - name: NODE_ENV
           value: development
         - name: PRODUCT_SERVICE_APP_NAME
           value: Product Service
         - name: PRODUCT_SERVICE_APP_PORT
           value: "5000"
         - name: AUTH_HOST
           value: auth-service
         - name: AUTH_SERVICE_TCP_PORT
           value: "5002"
         - name: PAYMENTS_HOST
           value: payments-service
         - name: PAYMENTS_TCP_PORT
           value: "5004"
        ports:
          - containerPort: 5000