apiVersion: v1
kind: Service
metadata:
  labels:
    app: products
  name: products
spec:
  ports:
  - name: "http"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: products
  type: NodePort
