apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments-service
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service
        # image: asia-south1-docker.pkg.dev/ecommerce-499513/payments-service/production
        image: 971598352479.dkr.ecr.ap-south-1.amazonaws.com/payments-service:latest #aws ecr repository pointing to the payments-service image
        imagePullPolicy: Always
        command: ["node"]
        args: ["services/payments-service/dist/main"]
        env:
          - name: NODE_ENV
            value: development
          - name: PAYMENTS_SERVICE_APP_NAME
            value: Payments Service
          - name: PAYMENTS_TCP_PORT
            value: "5004"
          - name: NOTIFICATION_HOST
            value: notification-service-tcp
          - name: NOTIFICATION_TCP_PORT
            value: "5008"
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: secret
        ports:
          # - containerPort: 5003 #If http port not required then remove this
          - containerPort: 5004
